const API_URL = "http://localhost:3001/birds";

const SEARCH_INPUT_DEBOUNCE_TIME_MS = 100;
const LOADING_EFFECT_DEBOUNCE_TIME_MS = 500;

export {
	API_URL,
	SEARCH_INPUT_DEBOUNCE_TIME_MS,
	LOADING_EFFECT_DEBOUNCE_TIME_MS,
};
