const API_URL = "http://localhost:3001/birds";

const SEARCH_INPUT_DEBOUNCE_TIME_MS = 100;
const LOADING_EFFECT_DEBOUNCE_TIME_MS = 500;
const NO_RESULTS_MESSAGE = "No results found";

export {
	API_URL,
	NO_RESULTS_MESSAGE,
	SEARCH_INPUT_DEBOUNCE_TIME_MS,
	LOADING_EFFECT_DEBOUNCE_TIME_MS,
};
